FROM node:10.16.0-alpine
RUN apk update && apk add --virtual build-dependencies build-base gcc wget git python2

WORKDIR /usr/src/app

COPY ./package.json .
RUN npm i -g @angular/cli concurrently
EXPOSE 4200
ENTRYPOINT npm install && npm run dev
